#*  This playbook wrapps the fetch module. It passes the webconfig
#* configured for each host as a list to 'src'. Use '-a' to pass
#* further parameters to ansible (as '-e'). See ansible fetch for
#* details. 
#*  You might want to do set a temporary workdir `nodeify.sh -w dir`
#* or do a `nodeify.sh merge-all` first and then merge manually back
#* to the storage dir. 
#*  No arguments are needed.

- hosts: role.webserver

  roles:
    - persist-web-vhosts

