# /etc/exim4/update-exim4.conf.conf
#
# Edit this file and /etc/mailname by hand and execute update-exim4.conf
# yourself or use 'dpkg-reconfigure exim4-config'
#
# Please note that this is _not_ a dpkg-conffile and that automatic changes
# to this file might happen. The code handling this will honor your local
# changes, so this is usually fine, but will break local schemes that mess
# around with multiple versions of the file.
#
# update-exim4.conf uses this file to determine variable values to generate
# exim configuration macros for the configuration file.
#
# Most settings found in here do have corresponding questions in the
# Debconf configuration, but not all of them.
#
# This is a Debian specific file

dc_eximconfig_configtype='{{ exim4__server_mode }}'
dc_other_hostnames='{{ exim4__mail_name }}'
dc_local_interfaces='127.0.0.1 ; ::1'
dc_readhost='{{ exim4__sender_domain }}'
dc_relay_domains=''
dc_minimaldns='false'
dc_relay_nets=''
dc_smarthost='{{ exim4__smart_host }}'
CFILEMODE='644'
dc_use_split_config='true'
dc_hide_mailname='{{ exim4__hide_mail_name }}'
dc_mailname_in_oh='true'
dc_localdelivery='mail_spool'

