

default__exim4__name: 'exim4'

default__exim4__client_credentials_file: '/etc/exim4/passwd.client'

default__exim4__client_user: ''

default__exim4__client_password: ''

default__exim4__server_mode: 'local'

default__exim4__smart_host: ''

default__exim4__hide_mail_name: ''

